from django.contrib import admin
from .models import *

admin.site.register(HallOfResidence)
admin.site.register(SocOrResearchGroup)
admin.site.register(MyUser)
admin.site.register(Event)
admin.site.register(Contact)
admin.site.register(Tag)
admin.site.register(Achievement)
admin.site.register(Grievance)
admin.site.register(InterIIT)
admin.site.register(GeneralChampionship)
admin.site.register(Posts)
admin.site.register(BillReimbursement)
admin.site.register(NotableAlumni)
admin.site.register(Department)
admin.site.register(Faculty)
admin.site.register(Subject)
admin.site.register(Course)
admin.site.register(CDCProfile)
admin.site.register(MediaFiles)
admin.site.register(News)
admin.site.register(CDCData)
admin.site.register(StudentProject)
admin.site.register(QuickLink)
admin.site.register(Activity)
admin.site.register(GovernorOrFounder)
admin.site.register(CDCStats)
admin.site.register(GCStats)